name: Noetic

on:
  push:

    branches: [ hw_api ]

  pull_request:
    branches: [ hw_api ]

  # schedule:
  #   - cron:  '0 0 * * *' # at the end of every day

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-20.04

    env:
      PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}

    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout CI scripts
        uses: actions/checkout@v3
        with:
          repository: ctu-mrs/ci_scripts
          path: .ci_scripts
          token: ${{ secrets.PUSH_TOKEN }}

      - name: Install ROS
        run: .ci_scripts/package_build/install_ros.sh

      - name: Build
        run: .ci_scripts/package_build/build_package.sh

      - name: Deploy
        run: .ci_scripts/package_build/deploy_deb.sh
